
# platform :ios, '6.0'

target 'SFProgressDemo' do
  pod 'SFProgressHUD', :git => 'https://github.com/looseyi/SFProgressHUD.git'
end

target 'SFProgressDemoTests' do

end

target 'SFProgressDemoUITests' do

end

